language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6

env:
  - MODULE_DIR=src/rikeripsum3

install:
  - pip install .
  - pip install pylint

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - pylint --errors-only $MODULE_DIR

after_success:
  - python setup.py sdist bdist_wheel
